apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: twitter-search-connector
  namespace: kafka
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: com.github.jcustenborder.kafka.connect.twitter.TwitterSourceConnector
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    key.converter.schemas.enable: false
    filter.keywords: kubernetes,apachekafka,strimzi
    kafka.status.topic: twitter-status
    kafka.delete.topic: twitter-status-deleted
    process.deletes: true
    twitter.oauth.accessToken: ${file:/opt/kafka/external-configuration/connector-config/twitter-credentials.properties:accessToken}
    twitter.oauth.accessTokenSecret: ${file:/opt/kafka/external-configuration/connector-config/twitter-credentials.properties:accessTokenSecret}
    twitter.oauth.consumerKey: ${file:/opt/kafka/external-configuration/connector-config/twitter-credentials.properties:consumerKey}
    twitter.oauth.consumerSecret: ${file:/opt/kafka/external-configuration/connector-config/twitter-credentials.properties:consumerSecret}
    camel.source.endpoint.count: 1